### ISSUE TITLE
滚动条美化 支持谷歌

### ISSUE THREAD

**Issue by Lee981265** [WEB-qq-635678224/JS-Note#56]
```js
  <div
       class="textArea"
       @mouseover="OverY = 'overlay'"
       @mouseout="OverY = 'hidden'"
       :style="`overflow-y:${OverY}`"
    >
   </div>
```

**Comment by Lee981265** [comment]
## CSS滚动条选择器（伪元素选择器）
- ::-webkit-scrollbar — 整个滚动条.
- ::-webkit-scrollbar-button — 滚动条上的按钮 (上下箭头).
- ::-webkit-scrollbar-thumb — 滚动条上的滚动滑块.
- ::-webkit-scrollbar-track — 滚动条轨道.
- ::-webkit-scrollbar-track-piece — 滚动条没有滑块的轨道部分.
- ::-webkit-scrollbar-corner — 当同时有垂直滚动条和水平滚动条时交汇的部分.
- ::-webkit-resizer — 某些元素的corner部分的部分样式(例:textarea的可拖动按钮).

```css
      &::-webkit-scrollbar {
        width: 6px;
        background-color: #fff;
      }
      &::-webkit-scrollbar-thumb {
        border-radius: 4px;
        box-shadow: inset 0 0 6px rgba(2, 26, 67, 0.1);
      }
      &::-webkit-scrollbar-track {
        border-radius: 4px;
        background-color: #fff;
      }
      &::-webkit-scrollbar-track-piece {
        background-color: #eff2fb;
        border-radius: 6px;
      }
```
