### ISSUE TITLE
CSS 小技巧

### ISSUE THREAD

**Issue by Lee981265** [WEB-qq-635678224/JS-Note#58]
### 画三角形
- 要点：将一个div的宽度和高度设置为0，然后设置边框样式

```css
.box{
    width: 0;
    height: 0;
    border-top: 50px solid black;
    border-right: 50px solid red;
    border-bottom: 50px solid green;
    border-left: 50px solid blue;
}
```
效果如图所示：
![](https://img2018.cnblogs.com/blog/1541422/201907/1541422-20190705142649044-1853580464.png)

- 将左右下边框设置成transparent，就可以画出一个三角形
```css
.box{
    width: 0;
    height: 0;
    border-top: 50px solid black;
    border-right: 50px solid transparent;
    border-bottom: 50px solid transparent;
    border-left: 50px solid transparent;
}
// 等效代码
.box{
    width: 0;
    height: 0;
    border: 50px solid transparent;
    border-top-color: black ;
}
```
效果图
![](https://img2018.cnblogs.com/blog/1541422/201907/1541422-20190705143339445-866259237.png)

- 将下边框的长度设置为0，实现一个最小空间的三角形
```css
.box{
    width: 0;
    height: 0;
    border-top: 50px solid black;
    border-right: 50px solid transparent;
    border-left: 50px solid transparent;
}
```
效果图
![](https://img2018.cnblogs.com/blog/1541422/201907/1541422-20190705143739430-180105466.png)

### 画圆
```css
.box{
  border-radius: 50%;
  width: 2rem;
  height: 2rem;
  background: #333;
}
```
